### ISSUE TITLE
install instructions / environment

### ISSUE THREAD

**Issue by denford** [peterkappus/nanodash#1]
Hey Peter,

Having some issues following the instructions, am wondering if it's an issue with my dev environment (node version, etc).

I install gulp globally, follow the steps then when trying to run `gulp` i get

```
[08:47:11] Warning: gulp version mismatch:
[08:47:11] Global gulp is 3.9.0
[08:47:11] Local gulp is 0.0.1
module.js:338
    throw err;
          ^
Error: Cannot find module 'gulp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mark/Dev/nanodash/gulpfile.js:1:81)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

I've tried under node.js 0.12.2 and 4.2.1 (similar error).

Do we need to run npm install on the package? Seems the `"name": "gulp",` in the package.json may conflict?

**Comment by peterkappus** [comment]
Hmm, I'm new to gulp myself so not 100% sure what to try. What happens if you `cd` into the project folder and then run `npm update gulp`? Did you run `npm install` from the project directory to install all the plugins, etc?

When I check my version(s) I get the following:

```
$ gulp -v
[20:40:16] CLI version 3.9.0
[20:40:16] Local version 3.5.6
```

FYI, I'm on node v0.10.28.

These threads might help:
https://github.com/gulpjs/gulp/issues/171
https://github.com/gulpjs/gulp/issues/140

Also, I believe the 0.0.1 version number in the package.json is for the gulpfile itself and doesn't mean anything to npm (or gulp). The version of gulp that it wants is ~3.5.0 (see line 7). Feel free to remove the version number entirely or otherwise tweak the package.json file if that helps. 

Let me know how it goes!

**Comment by denford** [comment]
ok cool using 0.10.28 and running `npm install` works - it didn't work on 0.12.2 or 4.2.1, i'll look into why separately (presumably version incompatibilities between items in package.json and the version of node).

now when i run `gulp` it runs better, gets further, still aborts with an error though so i'll look into this first then report back.

FYI output is:

```
[07:55:49] Warning: gulp version mismatch:
[07:55:49] Global gulp is 3.9.0
[07:55:49] Local gulp is 3.5.6
[07:55:50] Using gulpfile ~/Dev/nanodash/gulpfile.js
[07:55:50] Starting 'js'...
[07:55:50] Starting 'css'...
[07:55:50] Starting 'slim'...
[07:55:50] Finished 'slim' after 1.32 ms
[07:55:50] Starting 'templates'...
[07:55:50] Starting 'express'...
[07:55:50] Listening on port: 1337
[07:55:50] Finished 'express' after 1.79 ms
[07:55:50] Starting 'watch'...
[07:55:50] Finished 'watch' after 141 μs
[07:55:50] Finished 'css' after 17 ms
[07:55:50] Finished 'templates' after 14 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:904:11)
    at Object.afterWrite (net.js:720:19)
```

**Comment by peterkappus** [comment]
I've never seen that one but  you might try adding "stream-combiner2" (You'll need to add it to the package.json as well and tweaking the gulpfile to capture the error so you can get a better look at it.

Check out this recipe: https://github.com/gulpjs/gulp/blob/master/docs/recipes/combining-streams-to-handle-errors.md

**Comment by denford** [comment]
cool i'll check that out - i think the issue is that the files aren't being produced in the dist directory when gulp runs, need to see why

**Comment by denford** [comment]
aha! solved. inspired by this issue: https://github.com/paulnorthup/gulp-proto/issues/3#issuecomment-72357183 i realised i had to install slim: `gem install slim` and restart my terminal.

So this sum total of this issue is, i had to:
1. Use node 0.10.28
1. run `npm install`
1. run `gem install slim`

**Comment by peterkappus** [comment]
Ah, of course, I forgot that I had already installed Slim. This, unfortunately, introduces a Ruby dependency but it's a fairly mature templating language and one that I already knew... A future version might use Jade templates so it could be a fully JS stack with no Ruby required...

Feel free to tidy up the actual installation steps in the README to make them correct.

**Comment by denford** [comment]
cool i'll do that.
actually i haven't used github that much with other people, i've tried making a branch, committing some changes, and submitting a pull request which is my understanding of how this works, but then when submitting the pull request i get an authorisation error - is there something you need to do on the repo itself to allow pull requests?

**Comment by peterkappus** [comment]
Hmm, it sounds like you've done everything correctly and I don't think PRs need to be specifically enabled on the repo...Can you post the error you're getting?

**Comment by peterkappus** [comment]
Hey @denford I think it worked! Our first successful pull-request & merge. :) Do a quick pull to make sure everything looks good and we can carry on building. Meanwhile, I'll close this issue. Thanks for playing along!

**Comment by denford** [comment]
looks all good here, switched back to master branch, pulled down new changes including your latest
